### ISSUE TITLE
`voila notebook.ipynb --template=gridstack` no longer interactive?

### ISSUE THREAD

**Issue by Zabamund** [voila-dashboards/voila-gridstack#29]
A fantastic project and thank you for all your efforts to make it happen.

I have seen [this issue](https://github.com/voila-dashboards/voila-gridstack/issues/4) and updated with `pip install upgrade voila voila-gridstack` but when I run `voila notebook.ipynb --template=gridstack` I no longer get an interactive dashboard, in fact I get the output cells of the notebook but can no longer scroll the page.
I am on:
```
voila                     0.1.20                   pypi_0    pypi
voila-gridstack           0.0.7                    pypi_0    pypi
voila-vuetify             0.2.0                    pypi_0    pypi
jupyter                   1.0.0                    py37_7  
jupyter-server            0.1.1                    pypi_0    pypi
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.6.0                    py37_0  
jupyterlab                1.1.4              pyhf63ae98_0  
jupyterlab-pygments       0.1.0                    pypi_0    pypi
jupyterlab_server         1.0.6                      py_0  
```

if I run the same notebook with the `voila widget` in the jupyter notebook, I get the same output but in that case I _can_ scroll the page, I can just not rearrange the cells as previously.

EDIT:
I have checked and get the same behaviour both in Chromium 78.0.3904.97-1 and in Firefox 70.0.1-1

**Comment by dhinojosa** [comment]
Same... the arrows are fixed and immovable.

**Comment by SylvainCorlay** [comment]
The handles must be activated explicitely with

**Comment by dhinojosa** [comment]
@SylvainCorlay Yes, been running this...
```
 voila --template=gridstack . --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'  
```

It shows the handles but everything is fixed, immovable, and unable to scroll.

**Comment by dhinojosa** [comment]
Here is the visual. There are handles but they are immovable.
I ran:

```sh
voila ./2_Visualizations.ipynb --template=gridstack --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'
```

<img width="985" alt="Screen Shot 2020-01-02 at 5 06 08 PM" src="https://user-images.githubusercontent.com/410757/71700611-41bb1700-2d82-11ea-8a51-6d618a5f75b9.png">

**Comment by tina3005** [comment]
do we have any resolusion for this issue? i came up this error when add the configuration: traitlets.traitlets.TraitError: The 'resources' trait of a VoilaConfiguration instance must be a dict or None, but a value of class 'str' (i.e. '{gridstack: {show_handles: True}}') was specified.

**Comment by Zabamund** [comment]
I did the same as @tina3005, I ran this following @SylvainCorlay's message:

`voila notebook.ipynb --template=gridstack --VoilaConfiguration.resources='{“gridstack”: {“show_handles”: True}}'`

and I get this error:

```
Traceback (most recent call last):
  File "/home/geodev/anaconda3/envs/geocomp/bin/voila", line 8, in <module>
    sys.exit(main())
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/voila/app.py", line 347, in initialize
    self.voila_configuration = VoilaConfiguration(parent=self)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/config/configurable.py", line 84, in __init__
    self.config = config
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 1139, in _notify_trait
    type='change',
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 1176, in notify_change
    c(change)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 819, in compatible_observer
    return func(self, change)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/config/configurable.py", line 186, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/config/configurable.py", line 153, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 559, in set
    new_value = self._validate(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 2529, in validate
    value = super(Dict, self).validate(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'resources' trait of a VoilaConfiguration instance must be a dict or None, but a value of class 'str' (i.e. '{“gridstack”: {“show_handles”: True}}') was specified.
```

Calling the same without a `str`, like this:

`voila notebook.ipynb --template=gridstack --VoilaConfiguration.resources={“gridstack”: {“show_handles”: True}}` 

yields this error:

```
Traceback (most recent call last):
  File "/home/geodev/anaconda3/envs/geocomp/bin/voila", line 8, in <module>
    sys.exit(main())
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "/home/geodev/anaconda3/envs/geocomp/lib/python3.7/site-packages/voila/app.py", line 342, in initialize
    raise ValueError('provided more than 1 argument: %r' % self.extra_args)
ValueError: provided more than 1 argument: ['notebook.ipynb', '{“show_handles”:', 'True}}']
```

Is there anymore additional information I can provide to help in debugging this as I seem not to be the only one with the issue?

**Comment by AdamJel** [comment]
Hello, 
I would like to ask about progress with this issue, since it behaves the same for me. I cannot get pass the 'provided more than 1 argument' error.

Also, It would be great to hear, that there is an ongoing work on this template in general, since there has not been any commit for a while. 

@SylvainCorlay you have mentioned a WISIWYG editor for 2020. Is this still in plan? Could you provide some general roadmap for gridstack?

Thank you all. I am looking forward to progress here, since this is great project indeed.

**Comment by SylvainCorlay** [comment]
@AdamJel yes, we have significant work planed on this for this year, even if the current state is early stage.

We are walking up the stack in jupyter_client, nbconvert, and jupyter_server to improve the voilà performances. Work on the gridstack template should resume soon.

**Comment by AdamJel** [comment]
> 
> 
> @AdamJel yes, we have significant work planed on this for this year, even if the current state is early stage.

This is so great to hear. OK, I am looking forward to it.

**Comment by mariobuikhuizen** [comment]
The 'provided more than 1 argument' error is caused by the wrong quote character `“` instead of `"`. It should be: `--VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'`

I can't reproduce the immovable items.

**Comment by Zabamund** [comment]
Following @mariobuikhuizen comment, I ran:
`voila mynotebook.ipynb --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'`
The notebook now renders and the interactivity is preserved, I can also scroll the notebook.
Thank you. It did indeed fix that error.

The behaviour is the same if I run:
`voila mynotebook.ipynb` 

I saw that
> Work on the gridstack template should resume soon.

so I'll wait, and once again, thank you to the devs for this awesome project.

**Comment by flobrec** [comment]
I'm trying to run the VoilaConfiguration.resources as used by Zabamund, however run into the following problem when using Anaconda powershell:
(conda-env) PS C:\Users\all\Documents\Python\PythonScripts\voila\voila\notebooks> voila bqplot.ipynb --VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'
Traceback (most recent call last):
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\Scripts\voila-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\voila\app.py", line 347, in initialize
    self.voila_configuration = VoilaConfiguration(parent=self)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\config\configurable.py", line 84, in __init__
    self.config = config
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 574, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 1134, in _notify_trait
    self.notify_change(Bunch(
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 1176, in notify_change
    c(change)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 819, in compatible_observer
    return func(self, change)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\config\configurable.py", line 186, in _config_changed
    self._load_config(change.new, traits=traits, section_names=section_names)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\config\configurable.py", line 153, in _load_config
    setattr(self, name, deepcopy(config_value))
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 559, in set
    new_value = self._validate(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 2529, in validate
    value = super(Dict, self).validate(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "C:\Users\all\Documents\Python\PythonScripts\voila\conda-env\lib\site-packages\traitlets\traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'resources' trait of a VoilaConfiguration instance must be a dict or None, but a value of class 'str' (i.e. '{gridstack: {show_handles: True}}') was specified.

Versions are as shown below, I set up a new environment in Anaconda3 and only installed pandas, bqplot, voila and voila-gridstack.

Any idea how I could avoid the dict issue?

**Comment by MridulS** [comment]
@flobrec when copying the command to command line, make sure to check the double quotes are correctly copied. Just rewrite the last part of command, this worked for me.

This one constructs a dictionary.
```
--VoilaConfiguration.resources='{"gridstack": {"show_handles": True}}'
```

This one ends up being a string (look at the double quotes).
```
--VoilaConfiguration.resources='{“gridstack”: {“show_handles”: True}}'
```

**Comment by silva-fabiofreitas** [comment]
I managed to run as follows on win10:

voila --template=gridstack Estatistica.ipynb --VoilaConfiguration.resources=**"{'gridstack': {'show_handles': True}}"**

inverted single quotes by double
@AdamJel  @SylvainCorlay  @Zabamund

**Comment by AdamJel** [comment]
Hi, @SylvainCorlay 

> For 2020, we plan on putting together a WYSIWYG editor for the layouts in JupyterLab.

I didn't find anything on jupyter blog and I don't know, if there is some roadmap somewhere? So, let me ask here: are there any news on the WYSIWYG editor, please? Is it still on plan? Can you guess a release date?

I am looking forward to this feature. Best of luck and thank you :)
